export default {
    view: [
        { label: '新建', component: 'ViewNewComponent' },
        { label: '列表', component: 'ViewListComponent' },
        { label: '日志', component: 'ViewLogComponent' },
    ],
    viewIndex: 1,
    project: [
        { name: '项目1', path: '/asdasd', dev: false, build: false, version: '0.0.1' },
        { name: '项目2', path: '/asdasd', dev: false, build: false, version: '0.0.1' },
        { name: '项目3', path: '/asdasd', dev: true, build: false, version: '0.0.1' },
        { name: '项目4', path: '/asdasd', dev: false, build: false, version: '0.0.1' },
        { name: '项目5', path: '/asdasd', dev: false, build: false, version: '0.0.1' },
        { name: '项目6', path: '/asdasd', dev: false, build: true, version: '0.0.1' },
        { name: '项目7', path: '/asdasd', dev: false, build: false, version: '0.0.1' },
        { name: '项目8', path: '/asdasd', dev: false, build: false, version: '0.0.1' },
        { name: '项目9', path: '/asdasd', dev: false, build: false, version: '0.0.1' },
        { name: '项目10', path: '/asdasd', dev: false, build: false, version: '0.0.1' },
        { name: '项目11', path: '/asdasd', dev: false, build: false, version: '0.0.1' },
        { name: '项目12', path: '/asdasd', dev: false, build: false, version: '0.0.1' },
        { name: '项目13', path: '/asdasd', dev: false, build: false, version: '0.0.1' },
        { name: '项目14', path: '/asdasd', dev: false, build: false, version: '0.0.1' },
        { name: '项目15', path: '/asdasd', dev: false, build: false, version: '0.0.1' },
        { name: '项目16', path: '/asdasd', dev: false, build: false, version: '0.0.1' },
        { name: '项目17', path: '/asdasd', dev: false, build: false, version: '0.0.1' },
        { name: '项目18', path: '/asdasd', dev: false, build: false, version: '0.0.1' },
        { name: '项目19', path: '/asdasd', dev: false, build: false, version: '0.0.1' },
    ],
    projectActiveIndex: 0,
};
